name: Build EXE
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install what is needed
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller lxml openpyxl
    - name: Build the executable
      run: pyinstaller --onefile --windowed my_script.py
    - name: Upload the file
      uses: actions/upload-artifact@v4
      with:
        name: main
        path: dist/main.exe
